

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: meuelevador.com
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
    volumes:
      - ./config/mail-data/:/var/mail
      - ./config/mail-state/:/var/mail-state
      - ./config/mail-logs/:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - ./config/ssl:/etc/letsencrypt
      - ./config/dkim:/tmp/docker-mailserver/opendkim/keys
    env_file:
      - ./config/.env
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    stop_grace_period: 1m

